### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hjwp** [gabrielfalcao/markment#3]
First hurdle:  requirements.txt specifies a version of Flask which won't work under Python 3:

```
Downloading/unpacking flask==0.9 (from markment==0.2.21)
  Using download cache from /home/harry/.pip-download-cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FF%2FFlask%2FFlask-0.9.tar.gz
  Running setup.py (path:/home/harry/.virtualenvs/lettuce/build/flask/setup.py) egg_info for package flask
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/harry/.virtualenvs/lettuce/build/flask/setup.py", line 62
        print "Audit requires PyFlakes installed in your system."
                                                                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/harry/.virtualenvs/lettuce/build/flask/setup.py", line 62

    print "Audit requires PyFlakes installed in your system."

                                                            ^

SyntaxError: invalid syntax

```

**Comment by nikolas** [comment]
There's a pull request for this here: #4
